# Generated by Django 4.2.25 on 2025-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('english_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metric_quantity', models.IntegerField()),
                ('unit_type', models.CharField(choices=[('tsp', 'teaspoon'), ('tablespoon', 'tbsp'), ('cup', 'cup'), ('gallon', 'gal.'), ('ounce', 'oz'), ('fluid ounce', 'fl oz'), ('pound', 'lb'), ('gram', 'g'), ('kilogram', 'kg'), ('milliliter', 'mL'), ('liter', 'L')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('cooking_method', models.CharField(choices=[('bake', 'Bake'), ('boil', 'Boil'), ('steam', 'Steam'), ('roast', 'Roast.'), ('braise', 'Braise'), ('fry', 'Fry'), ('airfry', 'Air Fry'), ('stirfry', 'Stir Fry')], max_length=50)),
                ('step_action', models.CharField(choices=[('stir', 'Stir'), ('mix', 'Mix'), ('cream', 'Cream'), ('blend', 'Blend'), ('whisk', 'Whisk'), ('puree', 'Puree'), ('whip', 'Whip'), ('fold', 'Fold'), ('add', 'Add')], max_length=50)),
                ('step_ingredient', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=100)),
                ('flaver_profile', models.CharField(choices=[('sweet', 'Sweet'), ('sour', 'Sour'), ('salty', 'Salty'), ('bitter', 'Bitter'), ('umami', 'Umami'), ('spicy', 'Spicy'), ('acidic', 'Acidic'), ('vibrant', 'Vibrant'), ('delicate', 'Delicate'), ('asian', 'Asian'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('indian', 'Indian'), ('italian', 'Italian'), ('mediterranean', 'Mediterranean'), ('slavic', 'Slavic'), ('russian', 'Russian'), ('jewish', 'Jewish'), ('british', 'British'), ('weird', 'Weird')], max_length=50)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
                ('steps', models.ManyToManyField(to='recipes.step')),
            ],
        ),
    ]
